name: Ubuntu Release

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Pack Resources
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          mkdir ${{github.workspace}}/release/
          cp ${{github.workspace}}/build/TDGame ${{github.workspace}}/release/
          cp -r ${{github.workspace}}/resource/maps/ ${{github.workspace}}/release/

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          type: "zip"
          directory: ${{github.workspace}}/release/
          filename: "TDGame-ubuntu-${{github.ref_name}}.zip"

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: "${{github.workspace}}/release/TDGame-ubuntu-${{github.ref_name}}.zip"
