name: Windows Release

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.svg"
      - "**.png"

env:
  BUILD_TYPE: Release
  BUILD_DIR: ${{github.workspace}}\build
  RELEASE_DIR: ${{github.workspace}}\release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: jurplel/install-qt-action@v4
        with:
          version: "6.2.4"
          cache: true
          arch: "win64_mingw"
          modules: qtmultimedia

      - name: Configure CMake
        run: cmake -G "MinGW Makefiles" -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{env.BUILD_DIR}} --config ${{env.BUILD_TYPE}}

      - name: Pack Resources
        # if: startsWith(github.ref, 'refs/tags/v')
        run: |
          mkdir ${{env.RELEASE_DIR}} -Force
          Xcopy ${{env.BUILD_DIR}}\TDGame.exe ${{env.RELEASE_DIR}}
          Xcopy /E /I ${{github.workspace}}\resource\maps ${{env.RELEASE_DIR}}\maps
          ${{env.QT_ROOT_DIR}}\bin\windeployqt.exe ${{env.RELEASE_DIR}}\TDGame.exe

      - uses: thedoctor0/zip-release@0.7.5
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          type: "zip"
          directory: ${{env.RELEASE_DIR}}
          filename: "TDGame-Windows-${{github.ref_name}}.zip"

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: "${{env.RELEASE_DIR}}/TDGame-windows-${{github.ref_name}}.zip"
