name: macOS Release

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.svg"
      - "**.png"

env:
  BUILD_TYPE: Release
  BUILD_DIR: ${{github.workspace}}/build
  RELEASE_DIR: ${{github.workspace}}/release

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-13
            arch: x86_64
            qt_arch: clang_64
          - os: macos-13
            arch: arm64
            qt_arch: clang_64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Ensure Rosetta is installed
        run: |
          if [[ $(uname -m) == "arm64" ]]; then
            if ! command -v /usr/bin/arch &> /dev/null; then
              softwareupdate --install-rosetta --agree-to-license
            fi
          fi

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.2.4"
          cache: true
          target: desktop
          modules: qtmultimedia
          arch: ${{ matrix.qt_arch }}

      - name: Configure CMake
        run: |
          if [[ $(uname -m) == "arm64" ]]; then
            arch -x86_64 cmake -B ${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }}
          else
            cmake -B ${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }}
          fi

      - name: Build
        run: cmake --build ${{env.BUILD_DIR}} --config ${{env.BUILD_TYPE}}

      - name: Pack Resources
        # if: startsWith(github.ref, 'refs/tags/v')
        run: |
          cp -r ${{github.workspace}}/resource/maps/ ${{env.RELEASE_DIR}}
          cp -r ${{env.BUILD_DIR}}/TDGame.app ${{env.RELEASE_DIR}}
          ${{env.QT_ROOT_DIR}}/bin/macdeployqt ${{env.RELEASE_DIR}}/TDGame.app

      - uses: thedoctor0/zip-release@0.7.5
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          type: "zip"
          directory: ${{env.RELEASE_DIR}}
          filename: "TDGame-macOS-${{ matrix.arch }}-${{github.ref_name}}.zip"

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: "${{env.RELEASE_DIR}}/TDGame-macos-${{ matrix.arch }}-${{github.ref_name}}.zip"
