name: Ubuntu Release

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.svg"
      - "**.png"

env:
  BUILD_TYPE: Release
  BUILD_DIR: ${{github.workspace}}/build
  RELEASE_DIR: ${{github.workspace}}/release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: jurplel/install-qt-action@v4
        with:
          version: "6.2.4"
          cache: true
          target: desktop
          modules: qtmultimedia

      - name: Configure CMake
        run: CMAKE_OSX_ARCHITECTURES=arm64;x86_64 cmake -B ${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{env.BUILD_DIR}} --config ${{env.BUILD_TYPE}}

      - name: Pack Resources
        # if: startsWith(github.ref, 'refs/tags/v')
        run: |
          mkdir -p ${{env.RELEASE_DIR}}
          cp ${{env.BUILD_DIR}}/TDGame ${{env.RELEASE_DIR}}
          cp -r ${{github.workspace}}/resource/maps/ ${{env.RELEASE_DIR}}

      - uses: thedoctor0/zip-release@0.7.5
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          type: "zip"
          directory: ${{env.RELEASE_DIR}}
          filename: "TDGame-ubuntu-${{github.ref_name}}.zip"

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: "${{env.RELEASE_DIR}}/TDGame-ubuntu-${{github.ref_name}}.zip"
