name: Windows Release

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.svg"
      - "**.png"

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: jurplel/install-qt-action@v4
        with:
          version: "5.15.2"
          arch: "win64_mingw81"

      - name: Configure CMake
        run: cmake -G "MinGW Makefiles" -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}\build --config ${{env.BUILD_TYPE}}

      - name: Pack Resources
        # if: startsWith(github.ref, 'refs/tags/v')
        run: |
          mkdir ${{github.workspace}}\release
          Xcopy ${{github.workspace}}\build\TDGame.exe ${{github.workspace}}\release
          Xcopy /E /I ${{github.workspace}}\resource\maps ${{github.workspace}}\release\maps
          ${{env.Qt5_Dir}}\bin\windeployqt.exe ${{github.workspace}}\release\TDGame.exe

      - uses: thedoctor0/zip-release@0.7.5
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          type: "zip"
          directory: ${{github.workspace}}/release/
          filename: "TDGame-Windows-${{github.ref_name}}.zip"

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: "${{github.workspace}}/release/TDGame-windows-${{github.ref_name}}.zip"
