name: macOS Release

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-13
            arch: x86_64
            qt_version: "5.15.2"
          - os: macos-latest
            arch: arm64
            qt_version: "5.15.2"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt_version }}
          target: desktop

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Pack Resources
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          mkdir ${{github.workspace}}/release/  
          cp ${{github.workspace}}/build/TDGame ${{github.workspace}}/release/  
          cp -r ${{github.workspace}}/resource/maps/ ${{github.workspace}}/release/

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          type: "zip"
          directory: ${{github.workspace}}/release/
          filename: "TDGame-macOS-${{ matrix.arch }}-${{github.ref_name}}.zip"

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: "${{github.workspace}}/release/TDGame-macOS-${{ matrix.arch }}-${{github.ref_name}}.zip"
